"""ActEval: evaluation tools for actuarial predictive models."""

from acteval.api import (
    compare,
    compare_distributions,
    evaluate,
    evaluate_distribution,
)
from acteval.distributions import (
    EmpiricalDistribution,
    GammaDistribution,
    LognormalDistribution,
    NegativeBinomialDistribution,
    PoissonDistribution,
    TweedieDistribution,
)
from acteval.metrics import (
    ae_ratio,
    brier_score,
    calibration_by_quantile,
    central_prediction_interval,
    crps,
    distribution_interval_coverage,
    distribution_interval_score,
    distribution_interval_width,
    distribution_quantile_score,
    gamma_deviance,
    gini,
    interval_score,
    large_loss_bias,
    lift,
    lift_by_quantile,
    log_score,
    mae,
    mean_interval_width,
    normalized_gini,
    poisson_deviance,
    prediction_interval_coverage,
    predictive_entropy,
    predictive_variance,
    quantile_score,
    risk_group_lift,
    rmse,
    tail_ae_ratio,
    tail_mae,
    tail_rmse,
    tweedie_deviance,
    weighted_calibration_error,
)
from acteval.plotting import (
    plot_calibration,
    plot_lift,
    plot_residuals,
    plot_tail_diagnostics,
)
from acteval.registry import MetricDefinition, get_metric, list_metrics
from acteval.reports import (
    CalibrationTable,
    ComparisonResult,
    EvaluationResult,
    LiftTable,
)
from acteval.types import MetricSpec, PredictiveDistribution, Task

__all__ = [
    "CalibrationTable",
    "ComparisonResult",
    "EmpiricalDistribution",
    "EvaluationResult",
    "GammaDistribution",
    "LiftTable",
    "LognormalDistribution",
    "MetricDefinition",
    "MetricSpec",
    "NegativeBinomialDistribution",
    "PoissonDistribution",
    "PredictiveDistribution",
    "Task",
    "TweedieDistribution",
    "ae_ratio",
    "brier_score",
    "calibration_by_quantile",
    "central_prediction_interval",
    "compare",
    "compare_distributions",
    "crps",
    "distribution_interval_coverage",
    "distribution_interval_score",
    "distribution_interval_width",
    "distribution_quantile_score",
    "evaluate",
    "evaluate_distribution",
    "gamma_deviance",
    "get_metric",
    "gini",
    "interval_score",
    "large_loss_bias",
    "lift",
    "lift_by_quantile",
    "list_metrics",
    "log_score",
    "mae",
    "mean_interval_width",
    "normalized_gini",
    "plot_calibration",
    "plot_lift",
    "plot_residuals",
    "plot_tail_diagnostics",
    "poisson_deviance",
    "prediction_interval_coverage",
    "predictive_entropy",
    "predictive_variance",
    "quantile_score",
    "risk_group_lift",
    "rmse",
    "tail_ae_ratio",
    "tail_mae",
    "tail_rmse",
    "tweedie_deviance",
    "weighted_calibration_error",
]

__version__ = "0.2.0"
